---
- name: download wordpress
  become: yes
  become_user: "{{ arwp_user_name }}"
  command: >-
    wp core download --path="{{ arwp_fact_wordpress_path }}" {{ '--locale="'
    + arwp_wordpress_locale + '"' if arwp_wordpress_locale else '' }} {{
    '--version="' + arwp_wordpress_version + '"' if arwp_wordpress_version
    is regex('^[0-9]\.[0-9]\.?[0-9]?$') else '' }}
  args:
    chdir: "{{ arwp_fact_wordpress_path }}"
