---
- name: set fact wordpress path
  set_fact:
    arwp_fact_wordpress_path: >-
      {{ arwp_install_path }}/{{ arwp_install_folder_name }}

- name: check install directory existence
  file:
    path: "{{ arwp_fact_wordpress_path }}"
    state: directory
    owner: "{{ arwp_user_name }}"
    group: "{{ arwp_group_name }}"
    mode: "{{ arwp_install_folder_mode }}"

- name: template wp-config.php
  template:
    src: wp-config.php.j2
    dest: "{{ arwp_fact_wordpress_path }}/wp-config.php"
    owner: "{{ arwp_wpconfig_owner }}"
    group: "{{ arwp_wpconfig_group }}"
    mode: "{{ arwp_wpconfig_mode }}"

- name: verify checksums for wordpress files
  command: wp --allow-root core verify-checksums
  args:
    chdir: "{{ arwp_fact_wordpress_path }}"
  register: arwp_result_checksums
  ignore_errors: yes
  changed_when: false

- debug: var=arwp_result_checksums
  tags: [never, debug]

- name: download wordpress
  become: yes
  become_user: "{{ arwp_user_name }}"
  command: >-
    wp core download --path="{{ arwp_fact_wordpress_path }}" {{ '--locale="'
    + arwp_wordpress_locale + '"' if arwp_wordpress_locale else '' }} {{
    '--version="' + arwp_wordpress_version + '"' if arwp_wordpress_version
    is regex('^[0-9]\.[0-9]\.?[0-9]?$') else '' }}
  args:
    chdir: "{{ arwp_fact_wordpress_path }}"
  when: arwp_result_checksums.rc != 0

- name: check if wordpress is installed
  command: wp --allow-root core is-installed
  register: arwp_result_is_installed
  ignore_errors: yes
  changed_when: false

- debug: var=arwp_result_is_installed
  tags: [never, debug]

- name: install wordpress
  become: yes
  become_user: "{{ arwp_user_name }}"
  command: >-
    wp --path={{ arwp_fact_wordpress_path }} core install
    --url="{{ arwp_blog_url }}"
    --title="{{ arwp_blog_title }}"
    --admin_user="{{ arwp_blog_admin_user }}"
    --admin_password="{{ arwp_blog_admin_pass }}"
    --admin_email="{{ arwp_blog_admin_email }}"
    {{ '--skip-email' if arwp_blog_skip_email else '' }}
  args:
    chdir: "{{ arwp_fact_wordpress_path }}"
  no_log: true
  when: arwp_result_is_installed.rc != 0

# - name: get wordpress installed version
#   command: wp --allow-root core version
#   args:
#     chdir: "{{ arwp_fact_wordpress_path }}"
#   register: arwp_result_wordpress_version
#   when: arwp_fact_wordpress_installed == true and arwp_wordpress_version != ""