---
- name: set fact wordpress path
  set_fact:
    arwp_fact_wordpress_path: >-
      {{ arwp_install_path }}/{{ arwp_install_folder_name }}

- name: import tasks related to install path and wp-config.php
  import_tasks: wp_config.yml

#-------------------------------------------------------------------------------
# Download
#-------------------------------------------------------------------------------
- name: verify checksums for wordpress files
  command: wp --allow-root core verify-checksums
  args:
    chdir: "{{ arwp_fact_wordpress_path }}"
  register: arwp_result_checksums
  ignore_errors: yes
  changed_when: false

- name: stat {{ arwp_blog_download_creates }}
  stat:
    path: "{{ arwp_blog_download_creates }}"
  register: arwp_result_blog_download_creates

- name: import download tasks
  import_tasks: download.yml
  when: arwp_result_checksums.rc != 0

- block:
    - name: get downloaded version
      command: wp --allow-root core version
      args:
        chdir: "{{ arwp_fact_wordpress_path }}"
      register: arwp_result_core_version
      ignore_errors: yes
      changed_when: false

    - name: import tasks to be run when versions differs
      import_tasks: install_version_differs.yml
      when: >-
        arwp_wordpress_version is version(arwp_result_core_version.stdout, '<>')
  when: ( arwp_result_checksums.rc == 0
    or arwp_result_blog_download_creates.stat.exists )
    and arwp_wordpress_version is regex('^[0-9]\.[0-9]\.?[0-9]?$')

#-------------------------------------------------------------------------------
# Install
#-------------------------------------------------------------------------------
- name: check if wordpress is installed
  command: wp --allow-root core is-installed
  args:
    chdir: "{{ arwp_fact_wordpress_path }}"
  register: arwp_result_is_installed
  ignore_errors: yes
  changed_when: false

- name: install wordpress
  become: yes
  become_user: "{{ arwp_user_name }}"
  command: >-
    wp --path={{ arwp_fact_wordpress_path }} core install
    --url="{{ arwp_blog_url }}"
    --title="{{ arwp_blog_title }}"
    --admin_user="{{ arwp_blog_admin_user }}"
    --admin_password="{{ arwp_blog_admin_pass }}"
    --admin_email="{{ arwp_blog_admin_email }}"
    {{ '--skip-email' if arwp_blog_skip_email else '' }}
  args:
    chdir: "{{ arwp_fact_wordpress_path }}"
  no_log: true
  when: arwp_result_is_installed.rc != 0
