---
#-------------------------------------------------------------------------------
# Wp-cli
#-------------------------------------------------------------------------------
- name: check if wp-cli is installed
  command: wp --allow-root --info
  register: arwp_result_wpcli_info0
  ignore_errors: yes
  changed_when: false

- debug: var=arwp_result_wpcli_info0
  tags: [never, debug]

- block:
    - name: download wp-cli phar file
      get_url:
        url: "{{ __arwp_wpcli_download_url }}"
        dest: >-
          {{ __arwp_wpcli_phar_final_path }}/{{
          __arwp_wpcli_phar_final_filename }}
        mode: "{{ __arwp_wpcli_phar_filemode }}"

    # Testing as wordpress user to prevent errors originated from
    # missconfigured file permissions (closer to how it will be used).
    - name: test wp-cli installation
      become: yes
      command: "{{ __arwp_wpcli_phar_final_filename }} --info"
      register: arwp_result_wpcli_info1
      changed_when: false

    - debug: var=arwp_result_wpcli_info1
      tags: [never, debug]

    - name: assert correct execution of wp-cli
      assert:
        that:
          - arwp_result_wpcli_info1.rc == 0
        success_msg: wp --info correctly executed
        fail_msg: error while executing wp-cli
  # Alternatively use rc == 127?
  when: arwp_result_wpcli_info0.rc != 0